#
# Jekyll configuration
#
auto: true
permalink: /:title
pygments: true
lsi: true
markdown: rdiscount
rdiscount
  extensions: [smart]

#
# Site configuration
#
base_url: http://example.com
url: http://example.com
title: "le titre de votre site"
description: "La meta description sur la page d'accueil de votre site"
author: "Votre nom"
email: "votre-email@example.com"
gauaid: "UA-XXXXXXX-X" # Votre numéro de tracking Google Analytics
disqusid: "http://xxx.disqus.com" # Votre identifiant Disqus, de la forme http://xxx.disqus.com